### ISSUE TITLE
Add chart: Prices over time for item category

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#40] opened 2023-09-08 09:44 UTC
Chart details:

- [ ] Type: Scatter plot
- [ ] Title: Prices over time for item category
- [ ] Description: Identify price disparity in specific item categories.
- [ ] X-axis → Month & Year
- [ ] Y-axis → Unit Price ($USD)

Additional details:
- Chart is for a specific item category only. 
- Users can select the item category using a dropdown.

**Comment by vgeryarbc** [comment] 2023-10-19 10:16
How to calculate unit price per item category? Item category contains many items. 
Average unit price for item category over time does have a little sense because different category items procured over time.

**Comment by vgeryarbc** [comment] 2023-10-23 08:03
Thanks @jpmckinney, that helps ! 
1.  Item Categories have hierarchy (I've seen 3 levels in cpc). That probably requires another way for filtering (and sometimes showing) ItemCategories on dashboards.
2. I'll try to calculate item category average targeting on the third (lowest) hierarchy level in the way you described.

**Comment by Camilamila** [comment] 2023-10-25 10:11
That sounds good! We can see what results we get using 3 levels and adjust if needed.

**Comment by jpmckinney** [comment] 2023-10-25 14:52
>  That probably requires another way for filtering (and sometimes showing) ItemCategories on dashboards.

@vgeryarbc Is this related to the issues you were describing on the Price dashboard?

**Comment by vgeryarbc** [comment] 2023-10-25 20:31
Yes. Following today's meeting details:
1. Many items  (awards/items) belong to 2-nd  level of ItemCategory hierarchy (the lowest level is third. For 2023 year I didnt find any item relates to the 3 level) 
2. Calculating ItemCategoryUnitPrice like =` SUM( ItemUnitAmount)/NumberOfCategoryItems ` gives huge deviation due to large amount of dfferent items within category level2. (You may open Price dashboard to analyze item unit price deviation through category)
3. For Items mapped to 3nd ItemCategory hierarchy level we can obtain ItemCategoryUnitPrice more accurate but time-related question still remains - What do we get for ItemCategoryUnitPrice over time. Number of category items are different from one period to another and Items from the same category are procured in April and are not procured in May. Thus,  average over time  does not reflect real price changes for the Item Category due to different nomenclature procured in each period of time.
Any idea?

**Comment by Camilamila** [comment] 2023-10-27 10:26
Hi Vadim, 
For more accurate price comparissons, we can use a more granular level.  Reviewing the data  we can use the variable `classification/id` and `classification/description`, not the `award/item/description`.  For 2023 this gives us >7000 different items categories, however for the comparissons we can just show the items that have been procured more times (>average).  This would apply for the charts and tables in this dashboard.

**Comment by jpmckinney** [comment] 2023-10-27 20:26
> Many items (awards/items) belong to 2-nd level of ItemCategory hierarchy (the lowest level is third. For 2023 year I didnt find any item relates to the 3 level)

I can find many item classifications at any level, in 2023:

```sql
SELECT
  data->>'ocid' ocid,
  data->>'date' date,
  item->'classification'->>'id' id,
  item->'classification'->>'scheme' scheme,
  code,
  description
FROM ecuador_sercop_bulk
CROSS JOIN jsonb_array_elements(data->'awards') award
CROSS JOIN jsonb_array_elements(value->'items') item
LEFT JOIN cpc ON LEFT(item->'classification'->>'id', 3) = code
WHERE data->>'date' LIKE '2023-%'
LIMIT 10;
```

**Comment by jpmckinney** [comment] 2023-10-27 20:32
> we can use the variable classification/id and classification/description, not the award/item/description, and then the unit/value/amount which would give us the unit price for that item category in a specific procedure. For 2023 this gives us >7000 different items categories

@Camilamila This seems more complicated than it needs to be. We can just use `/awards[]/items[]/classification/id` which has 7179 distinct values:

```sql
SELECT
  COUNT(DISTINCT(item->'classification'->>'id'))
FROM ecuador_sercop_bulk
CROSS JOIN jsonb_array_elements(data->'awards') award
CROSS JOIN jsonb_array_elements(value->'items') item
WHERE data->>'date' LIKE '2023-%';
```

```
 count 
-------
  7179
```

**Comment by jpmckinney** [comment] 2023-10-27 20:39
> for the comparissons we can just show the items that have been procured more times (>average)

The above query yields an average of 57.7 (414096 / 7179)

There are 1148 categories that are procured more than 57 times in 2023.

```sql
SELECT
  COUNT(*) count,
  item->'classification'->>'id' id
FROM ecuador_sercop_bulk
CROSS JOIN jsonb_array_elements(data->'awards') award
CROSS JOIN jsonb_array_elements(award->'items') item
WHERE
  data->>'date' LIKE '2023-%'
  AND item->'classification'->>'id' IS NOT NULL
GROUP BY id
HAVING COUNT(*) > 57
ORDER BY count;
```

**Comment by vgeryarbc** [comment] 2023-10-31 10:36
1. @jpmckinney  you are right.  3 category level exists for items (I forgot to disable 2-level filter while observing). 
2. Item category unit price (ICUP) calculation. Following the discussion above I would like to propose calculating ICUP as average of ItemUnitAmout for items within the same `/awards[]/items[]/classification/id `as @Camilamila proposed but exclude items have been procured less than 100 times (or another threshold like > 57 @jpmckinney calculated). What do you think?

**Comment by jpmckinney** [comment] 2023-10-31 14:12
(2) 100 sounds like a good threshold.

**Comment by jpmckinney** [comment] 2023-11-01 14:28
@vgeryarbc @Camilamila On the call, we agreed to switch this to a line chart. The discussion on chart type included:
* Using a scatter plot won’t work, because popular item categories would yield a straight line of dots on the month line (e.g. 1,000 dots per month)
* If we want to communicate the distribution, we could consider violin plots – but we agreed that most people don’t know how to read violin plots.
* If we want to communicate the distribution, we could also use box plots (i.e. one box plot per month) – but there is already another chart with box plots, so we won't take this option for now.

@Camilamila also recommended using the median for the line, instead of the average.

**Comment by Camilamila** [comment] 2023-11-27 13:50
This chart show show the median value of awards[]/items[]/classification/id.  Do not aggregate.

**Comment by vgeryarbc** [comment] 2023-11-28 08:05
@Camilamila @jpmckinney 
 At present aggregations to Item category lowest level (L3) are shown. If we break down to awards[]/items[]/classification/id there is going to be a lot of messy lines.  
May be multisections approach makes sense. Please check the updated version. There is one section per each awards[]/items[]/classification/id.  What do you think ?

**Comment by Camilamila** [comment] 2023-11-28 10:18
Hi Vadim I really like this! Multisections instead of the lines on the same chart!

**Comment by jpmckinney** [comment] 2024-05-17 00:03
I assume this is completed per @Camilamila's last message. Camila, please re-open if not.

**Comment by jpmckinney** [comment] 2024-05-17 01:05
Actually, I can't tell if the chart is working.

**Comment by Camilamila** [comment] 2024-05-17 09:44
I think the problem is that the scale is to high for the actual values, e.g. the value is 12 and the scale in 50K so it looks like a flat line.  Can we make the axis not fixed?

**Comment by jpmckinney** [comment] 2024-05-17 17:12
I assume you didn't mean to close the issue.

**Comment by vgeryarbc** [comment] 2024-05-29 20:21
Y- Scale is auto-defined from the highest price value from all Item categories **selected**. Otherwise, it could be hard to compare categories. This visual provides analytical sense when some categories (not all by default) selected (from filter above or by other page visuals).

**Comment by jpmckinney** [comment] 2024-05-30 05:39
Maybe we are not seeing the same chart. This is what I see. If I scroll, they are all the same 0K. Something seems incorrect about the y-axis.

<img width="708" alt="Screenshot 2024-05-30 at 1 37 58 AM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/eaec3a84-0b83-487a-9562-35c4c5cfac9e">

**Comment by vgeryarbc** [comment] 2024-05-31 07:47
@jpmckinney, it is the correct chart (we are talking about the same). I have now just changed sorting and cards with higher price come first. When no category or Item classification points selected we are seeing them all (from  the highest to lowest price with the same scale). When  some categorie or  Item classifications  filtered or selected it looks like this. 
![image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/4034a17b-28ac-41e2-a795-ced26b9b660c)

**Comment by Camilamila** [comment] 2024-06-13 14:33
Thanks Vadim.  It looks better now with the sorting.  A couple of requests:

- Add in the description:  This chart shows only items that have been procured more than 100 times. 

Also considering issue [#128](https://github.com/open-contracting/bi.open-contracting.org/issues/128), if a user selects the top level category (3 digit CPC), this this chart would show individual charts for each lower level category, from that group.

**Comment by vgeryarbc** [comment] 2024-07-03 20:46
Description added and filter for items with  >100 contract processes applied.
Note >100 filters for all time (from 2018 till now) and doesnt depend on any other filters

![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/ee84ace9-66d1-446e-b8d7-abe92c426f30)

**Closed** 2024-07-04 12:32 UTC
Labels: Chart, EC: Prices
